<?php

namespace EB\RideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RideRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideRequestRepository extends EntityRepository
{
}
