<?php

namespace EB\RideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideRepository extends EntityRepository
{
}
