<?php

namespace EB\RideBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EB\UserBundle\Entity\User;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function countByUser(User $user)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select(
            $qb->expr()->count('c.id')
        );
        $qb->where(
            $qb->expr()->eq('c.user', ':user')
        );
        $qb->setParameter('user', $user);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
