<?php

namespace EB\RideBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RideRequestStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideRequestStatusRepository extends EntityRepository
{
}
