<?php

namespace EB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendRequestStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestStatusRepository extends EntityRepository
{
}
