<?php

namespace EB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param string $searchTerm
     * @return array
     */
    public function findUsersByUsername($user, $searchTerm)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.username != :user')
            ->andWhere('u.username LIKE :username')
            ->setParameters(array(
                'user' => $user->getUsername(),
                'username' => '%' . $searchTerm . '%',
            ));

        return $qb->getQuery()->getArrayResult();
    }
}
