<?php

namespace EB\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FriendRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestRepository extends EntityRepository
{
}
